"use client";

import { useState, useEffect, useCallback, useMemo } from 'react';
import { Incident, IncidentFilter, IncidentAnalytics, IncidentSeverity, IncidentStatus, IncidentImpact, IncidentNote, IncidentTimelineEvent, IncidentEvidence } from '@/types/incidents';

// Mock incident generator
function generateMockIncidents(count: number = 100): Incident[] {
  const severities: IncidentSeverity[] = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'];
  const statuses: IncidentStatus[] = ['OPEN', 'INVESTIGATING', 'CONTAINED', 'RESOLVED', 'CLOSED'];
  const impacts: IncidentImpact[] = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];
  const incidentTypes = ['Brute Force Attack', 'Data Breach', 'Malware Detection', 'Suspicious Login', 'Unauthorized Access', 'DDoS Attack', 'SQL Injection', 'XSS Attack'];
  const users = ['admin@sentinelx.com', 'analyst1@company.com', 'security@team.com', 'john.doe@company.com', 'jane.smith@company.com'];
  
  const countries = ['USA', 'Russia', 'China', 'North Korea', 'Iran', 'Brazil', 'India', 'Germany', 'UK', 'France'];
  const cities = {
    'USA': ['New York', 'San Francisco', 'Chicago', 'Seattle', 'Washington DC'],
    'Russia': ['Moscow', 'St. Petersburg', 'Novosibirsk'],
    'China': ['Beijing', 'Shanghai', 'Shenzhen', 'Guangzhou'],
    'North Korea': ['Pyongyang'],
    'Iran': ['Tehran', 'Mashhad', 'Isfahan'],
    'Brazil': ['São Paulo', 'Rio de Janeiro', 'Brasília'],
    'India': ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad'],
    'Germany': ['Berlin', 'Munich', 'Hamburg', 'Frankfurt'],
    'UK': ['London', 'Manchester', 'Birmingham', 'Glasgow'],
    'France': ['Paris', 'Marseille', 'Lyon', 'Toulouse']
  };

  const generateTimeline = (incidentId: string, createdAt: Date): IncidentTimelineEvent[] => {
    const events: IncidentTimelineEvent[] = [
      {
        id: `${incidentId}-triggered`,
        timestamp: createdAt,
        type: 'alert_triggered',
        title: 'Security Alert Triggered',
        description: 'Initial security alert was generated by the detection system.',
        author: 'System'
      }
    ];

    // Add random status changes
    const statusChanges = Math.floor(Math.random() * 3);
    for (let i = 0; i < statusChanges; i++) {
      const statusOptions: IncidentStatus[] = ['INVESTIGATING', 'CONTAINED', 'RESOLVED'];
      const randomStatus = statusOptions[Math.floor(Math.random() * statusOptions.length)];
      events.push({
        id: `${incidentId}-status-${i}`,
        timestamp: new Date(createdAt.getTime() + (i + 1) * 30 * 60 * 1000),
        type: 'status_change',
        title: `Status Changed to ${randomStatus}`,
        description: `Incident status was updated to ${randomStatus}.`,
        author: users[Math.floor(Math.random() * users.length)]
      });
    }

    // Add notes
    const noteCount = Math.floor(Math.random() * 2);
    for (let i = 0; i < noteCount; i++) {
      events.push({
        id: `${incidentId}-note-${i}`,
        timestamp: new Date(createdAt.getTime() + (statusChanges + i + 1) * 45 * 60 * 1000),
        type: 'note_added',
        title: 'Analyst Note Added',
        description: ['Investigation in progress', 'Additional evidence collected', 'Coordination with IT team', 'Escalation to senior analyst'][i],
        author: users[Math.floor(Math.random() * users.length)]
      });
    }

    return events;
  };

  return Array.from({ length: count }, (_, i) => {
    const severity = severities[Math.floor(Math.random() * severities.length)];
    const status = Math.random() < 0.3 ? 'OPEN' : statuses[Math.floor(Math.random() * (statuses.length - 1)) + 1];
    const impact = impacts[Math.floor(Math.random() * impacts.length)];
    const incidentType = incidentTypes[Math.floor(Math.random() * incidentTypes.length)];
    const country = countries[Math.floor(Math.random() * countries.length)];
    const cityList = cities[country as keyof typeof cities] || ['Unknown'];
    const city = cityList[Math.floor(Math.random() * cityList.length)];
    const createdAt = new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000);
    const resolutionTime = Math.floor(Math.random() * 48) + 1; // 1-48 hours
    const actualResolutionTime = status === 'RESOLVED' || status === 'CLOSED' ? new Date(createdAt.getTime() + resolutionTime * 60 * 60 * 1000) : undefined;
    const correlationId = Math.random() < 0.2 ? `corr-${Math.random().toString(36).substr(2, 9)}` : undefined;

    return {
      id: `incident-${Date.now()}-${i}`,
      title: `${incidentType} - ${city}`,
      description: `Security incident involving ${incidentType.toLowerCase()} detected from ${city}, ${country}. This incident requires immediate investigation and proper response procedures.`,
      severity,
      status,
      impact,
      createdAt,
      updatedAt: new Date(createdAt.getTime() + Math.random() * 24 * 60 * 60 * 1000),
      assignedTo: status !== 'OPEN' ? users[Math.floor(Math.random() * users.length)] : undefined,
      assignedToName: status !== 'OPEN' ? users[Math.floor(Math.random() * users.length)].split('@')[0] : undefined,
      affectedAssets: Array.from({ length: Math.floor(Math.random() * 3) + 1 }, (_, j) => ({
        id: `asset-${j}`,
        name: `Server-${j + 1}`,
        type: (['server', 'user', 'application', 'network', 'database'] as const)[Math.floor(Math.random() * 5)],
        ip: `${Math.floor(Math.random() * 255)}.${Math.floor(Math.random() * 255)}.${Math.floor(Math.random() * 255)}.${Math.floor(Math.random() * 255)}`,
        location: `${city}, ${country}`
      })),
      linkedAlerts: Array.from({ length: Math.floor(Math.random() * 5) + 1 }, (_, k) => `alert-${Date.now()}-${i}-${k}`),
      tags: [incidentType.toLowerCase().replace(' ', '-'), severity.toLowerCase(), impact.toLowerCase()],
      notes: [] as IncidentNote[],
      timeline: generateTimeline(`incident-${Date.now()}-${i}`, createdAt),
      riskScore: Math.floor(Math.random() * 100) + 1,
      estimatedResolutionTime: resolutionTime,
      actualResolutionTime,
      priority: severity === 'CRITICAL' ? 1 : severity === 'HIGH' ? 2 : severity === 'MEDIUM' ? 3 : 4,
      sourceAlertId: `alert-${Date.now()}-${i}`,
      correlationId,
      evidence: [] as IncidentEvidence[]
    };
  });
}

export function useIncidents(initialFilter: Partial<IncidentFilter> = {}) {
  const [incidents, setIncidents] = useState<Incident[]>([]);
  const [isClient, setIsClient] = useState(false);
  const [filter, setFilter] = useState<IncidentFilter>({
    search: '',
    severity: [],
    status: [],
    impact: [],
    assignedTo: '',
    dateRange: '7d',
    tags: [],
    ...initialFilter
  });
  const [isLoading, setIsLoading] = useState(false);
  const [selectedIncidentId, setSelectedIncidentId] = useState<string | null>(null);

  useEffect(() => {
    setIsClient(true);
    setIncidents(generateMockIncidents(150));
  }, []);

  // Simulate real-time updates
  useEffect(() => {
    const interval = setInterval(() => {
      const newIncidents = generateMockIncidents(Math.floor(Math.random() * 3) + 1);
      setIncidents(prev => [...newIncidents, ...prev].slice(0, 500));
    }, Math.random() * 15000 + 10000);

    return () => clearInterval(interval);
  }, []);

  // Filter incidents
  const filteredIncidents = useMemo(() => {
    return incidents.filter(incident => {
      // Search filter
      if (filter.search) {
        const searchLower = filter.search.toLowerCase();
        if (!incident.title.toLowerCase().includes(searchLower) &&
            !incident.description.toLowerCase().includes(searchLower) &&
            !incident.id.toLowerCase().includes(searchLower)) {
          return false;
        }
      }

      // Severity filter
      if (filter.severity?.length > 0 && !filter.severity.includes(incident.severity)) {
        return false;
      }

      // Status filter
      if (filter.status?.length > 0 && !filter.status.includes(incident.status)) {
        return false;
      }

      // Impact filter
      if (filter.impact?.length > 0 && !filter.impact.includes(incident.impact)) {
        return false;
      }

      // Assigned to filter
      if (filter.assignedTo && (!incident.assignedTo || !incident.assignedTo.includes(filter.assignedTo))) {
        return false;
      }

      // Tags filter
      if (filter.tags?.length > 0 && !filter.tags.some(tag => incident.tags.includes(tag))) {
        return false;
      }

      // Date range filter
      const now = new Date();
      let startTime: Date;
      
      switch (filter.dateRange) {
        case '24h':
          startTime = new Date(now.getTime() - 24 * 60 * 60 * 1000);
          break;
        case '7d':
          startTime = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
          break;
        case '30d':
          startTime = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
          break;
        case 'custom':
          startTime = filter.customStart || new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
          break;
        default:
          startTime = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
      }

      const endTime = filter.dateRange === 'custom' && filter.customEnd ? filter.customEnd : now;
      
      if (incident.createdAt < startTime || incident.createdAt > endTime) {
        return false;
      }

      return true;
    });
  }, [incidents, filter]);

  // Analytics
  const analytics = useMemo((): IncidentAnalytics => {
    const totalIncidents = filteredIncidents.length;
    const openIncidents = filteredIncidents.filter(incident => incident.status === 'OPEN').length;
    const criticalIncidents = filteredIncidents.filter(incident => incident.severity === 'CRITICAL').length;
    
    if (!isClient || totalIncidents === 0) {
      return {
        totalIncidents: 0,
        openIncidents: 0,
        criticalIncidents: 0,
        meanTimeToResolve: 0,
        medianTimeToResolve: 0,
        incidentsOverTime: [],
        incidentsBySeverity: [],
        incidentsByStatus: [],
        topIncidentTypes: [],
        resolutionRate: 0,
        escalationRate: 0,
        averageAlertsPerIncident: 0
      };
    }

    const resolvedIncidents = filteredIncidents.filter(incident => 
      incident.status === 'RESOLVED' || incident.status === 'CLOSED'
    );
    
    const resolutionTimes = resolvedIncidents
      .map(incident => incident.actualResolutionTime ? 
        (incident.actualResolutionTime.getTime() - incident.createdAt.getTime()) / (1000 * 60 * 60) : null)
      .filter((time): time is number => time !== null) as number[];
    
    const meanTimeToResolve = resolutionTimes.length > 0 ? 
      resolutionTimes.reduce((sum, time) => sum + time, 0) / resolutionTimes.length : 0;
    
    const medianTimeToResolve = resolutionTimes.length > 0 ? 
      resolutionTimes.sort((a, b) => a - b)[Math.floor(resolutionTimes.length / 2)] : 0;

    // Incidents over time (last 7 days)
    const incidentsOverTime = Array.from({ length: 7 }, (_, i) => {
      const time = new Date(Date.now() - (6 - i) * 24 * 60 * 60 * 1000);
      const count = filteredIncidents.filter(incident => {
        const incidentTime = new Date(incident.createdAt);
        return incidentTime >= time && incidentTime < new Date(time.getTime() + 24 * 60 * 60 * 1000);
      }).length;
      const critical = filteredIncidents.filter(incident => {
        const incidentTime = new Date(incident.createdAt);
        return incidentTime >= time && incidentTime < new Date(time.getTime() + 24 * 60 * 60 * 1000) && incident.severity === 'CRITICAL';
      }).length;
      
      return {
        time: time.toLocaleDateString([], { month: 'short', day: 'numeric' }),
        count,
        critical
      };
    });

    // Incidents by severity
    const severityCounts = filteredIncidents.reduce((acc, incident) => {
      acc[incident.severity] = (acc[incident.severity] || 0) + 1;
      return acc;
    }, {} as Record<IncidentSeverity, number>);

    const incidentsBySeverity = Object.entries(severityCounts)
      .map(([severity, count]) => ({ severity: severity as IncidentSeverity, count }))
      .sort((a, b) => {
        const severityOrder: Record<string, number> = { 'CRITICAL': 0, 'HIGH': 1, 'MEDIUM': 2, 'LOW': 3 };
        return (severityOrder[a.severity] ?? 99) - (severityOrder[b.severity] ?? 99);
      });

    // Incidents by status
    const statusCounts = filteredIncidents.reduce((acc, incident) => {
      acc[incident.status] = (acc[incident.status] || 0) + 1;
      return acc;
    }, {} as Record<IncidentStatus, number>);

    const incidentsByStatus = Object.entries(statusCounts)
      .map(([status, count]) => ({ status: status as IncidentStatus, count }))
      .sort((a, b) => b.count - a.count);

    // Top incident types
    const incidentTypes = filteredIncidents.map(incident => incident.title.split(' - ')[0]);
    const typeCounts = incidentTypes.reduce((acc, type) => {
      acc[type] = (acc[type] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    const topIncidentTypes = Object.entries(typeCounts)
      .map(([type, count]) => ({ type, count }))
      .sort((a, b) => b.count - a.count)
      .slice(0, 5);

    const resolutionRate = totalIncidents > 0 ? (resolvedIncidents.length / totalIncidents) * 100 : 0;
    const escalationRate = totalIncidents > 0 ? (criticalIncidents / totalIncidents) * 100 : 0;
    const averageAlertsPerIncident = filteredIncidents.length > 0 ? 
      filteredIncidents.reduce((sum, incident) => sum + incident.linkedAlerts.length, 0) / filteredIncidents.length : 0;

    return {
      totalIncidents,
      openIncidents,
      criticalIncidents,
      meanTimeToResolve,
      medianTimeToResolve,
      incidentsOverTime,
      incidentsBySeverity,
      incidentsByStatus,
      topIncidentTypes,
      resolutionRate,
      escalationRate,
      averageAlertsPerIncident
    };
  }, [filteredIncidents, isClient]);

  const updateFilter = useCallback((newFilter: Partial<IncidentFilter>) => {
    setFilter(prev => ({ ...prev, ...newFilter }));
  }, []);

  const clearFilter = useCallback(() => {
    setFilter({
      search: '',
      severity: [],
      status: [],
      impact: [],
      assignedTo: '',
      dateRange: '7d',
      tags: []
    });
  }, []);

  const updateIncidentStatus = useCallback((incidentId: string, status: IncidentStatus, assignedTo?: string) => {
    setIncidents(prev => prev.map(incident => 
      incident.id === incidentId 
        ? { 
            ...incident, 
            status, 
            updatedAt: new Date(),
            assignedTo: assignedTo || incident.assignedTo,
            assignedToName: assignedTo?.split('@')[0]
          }
        : incident
    ));
  }, []);

  const addNote = useCallback((incidentId: string, note: Omit<IncidentNote, 'id' | 'timestamp'>) => {
    const newNote: IncidentNote = {
      ...note,
      id: `note-${Date.now()}`,
      timestamp: new Date()
    };
    
    setIncidents(prev => prev.map(incident => 
      incident.id === incidentId 
        ? { ...incident, notes: [...incident.notes, newNote], updatedAt: new Date() }
        : incident
    ));
  }, []);

  const exportIncidents = useCallback((format: 'csv' | 'json') => {
    const data = format === 'csv' 
      ? convertToCSV(filteredIncidents)
      : JSON.stringify(filteredIncidents, null, 2);
    
    const blob = new Blob([data], { type: format === 'csv' ? 'text/csv' : 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `incidents-${new Date().toISOString()}.${format}`;
    a.click();
    URL.revokeObjectURL(url);
  }, [filteredIncidents]);

  return {
    incidents: isClient ? filteredIncidents : [],
    analytics,
    filter,
    isLoading: isLoading || !isClient,
    selectedIncidentId,
    updateFilter,
    clearFilter,
    setSelectedIncidentId,
    updateIncidentStatus,
    addNote,
    exportIncidents,
    refreshIncidents: () => setIncidents(generateMockIncidents(150))
  };
}

function convertToCSV(incidents: Incident[]): string {
  const headers = ['ID', 'Title', 'Severity', 'Status', 'Impact', 'Created At', 'Assigned To', 'Affected Assets', 'Linked Alerts'];
  const rows = incidents.map(incident => [
    incident.id,
    incident.title,
    incident.severity,
    incident.status,
    incident.impact,
    incident.createdAt.toISOString(),
    incident.assignedTo || '',
    incident.affectedAssets.map(asset => asset.name).join(';'),
    incident.linkedAlerts.join(';')
  ]);
  
  return [headers, ...rows].map(row => row.join(',')).join('\n');
}
